[package]
name = "data_types"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1-data_types"
path = "src/1-data_types.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
