[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "0-hello_world"
path = "src/0-hello_world.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
